COLUMNS:
  brand: 
    - value: string
  bullet_point: 
    - value: string
  color: null or string
  item_id: string
  item_name_in_en: 
    - value: string
  product_type: 
    - value: string
  style: 
    - value: string
  model_name:
    - value: string
  item_keywords: 
    - value: string
  bullet_point:
    - value: string
  path:
    - value: string
TARGET_COLUMN:
  name: item_id