artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-listings.tar
 # source_URL: https://drive.google.com/file/d/1OiiSV5u2elyYhovgH6_mCqReJsjZ8fJr/view?usp=sharing
 # The following archives are available for download:
 # LICENSE-CC-BY-4.0.txt — Copy of the CC BY 4.0 license https://amazon-berkeley-objects.s3.amazonaws.com/LICENSE-CC-BY-4.0.txt
 # README.md — Description of the dataset https://amazon-berkeley-objects.s3.amazonaws.com/README.md
 # abo-listings.tar — Product listings and metadata (83 Mb) https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-listings.tar
 # abo-images-original.tar — Original catalog images and metadata (110 Gb) https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-images-original.tar
 # abo-images-small.tar — Downscaled (max 256 pixels) catalog images and metadata (3 Gb) https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-images-small.tar
 # abo-spins.tar — 360º-view images and metadata (40 Gb) https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-spins.tar
 # abo-3dmodels.tar — 3D models (154 Gb) https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-3dmodels.tar
 # abo-mvr.csv.xz — Dataset splits for the CVPR22 Multi-View Retrieval experiments (4 Mb) https://amazon-berkeley-objects.s3.amazonaws.com/benchmarks/abo-mvr.csv.xz
 # abo-benchmark-material.tar — Rendered 3D models for the CVPR22 Material Prediction experiments (271 Gb) https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-benchmark-material.tar
 # abo-part-labels.tar — 3D part labels for the 3D Vision and Modeling Challenges in eCommerce ICCV 2023 Workshop Challenge (2 Gb) https://amazon-berkeley-objects.s3.amazonaws.com/archives/abo-part-labels.tar
  local_data_file: artifacts/data_ingestion/data.tar
  untar_path: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  untar_data_dir: artifacts/data_ingestion/data_tar_extracted/listings/metadata
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data_tar_extracted/listings/metadata

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_ingestion/data_tar_extracted/listings/metadata/Train/listings_0_train.json
  test_data_path: artifacts/data_ingestion/data_tar_extracted/listings/metadata/Test/listings_0_test.json
  model_name: model.joblib